[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
MouseActionCursor=0

[Metadata]
Name=Waifu - Portrait 2
Information=A character cutout. Edit ThisImage / ThisWidth below, or load several at once.
Version=1.0
License=MIT

[Variables]
@IncludeVariables=#@#Variables.inc
ThisImage=shorekeeper_portrait2.jpg
ThisWidth=300

[MeterWaifu]
Meter=Image
ImageName=#@#Images\#ThisImage#
X=0
Y=0
W=#ThisWidth#
PreserveAspectRatio=1
; ImageAlpha=235
